version: "3.9"

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data 
    environment:
      DATABASE_PATH: /data/travel.db
